---

# options unique to group tail analysis

partition:
  param_decls:
    - '-p'
    - '--partition'
  type:
    - 'country'
    - 'maturity'
    - 'core_vs_peripheral'
    - 'all'
  default: 'country'
  help: 'method for grouping tickers'
