#  Figure Information Templates (FIT) Defined Below



# # Tabled Figures FIT    # TODO: consider implement template inheritance for common fields (ax_table pos, etc.)

αf:   # α-fitting
  Plot_cls: 'TabledFigurePlotter'
  fig_name: 'Alpha fitting - ${label}'
  stats2plt: ['alpha']
  ax_title: |-
    Time evolution of $\alpha$ for ${label}
    Time period: ${timeperiod}
  ax_ylabel: '$\alpha$'
  ax_table:
    # TODO: many of these tail vec stats are included in anal results now, use directly?
    _cellText_gens: ['np.mean', 'np.median', 'np.std', 'np.min', 'np.max']
    _extra_cell: [['Right', 0], ['Left', 0]]  # int element repr insertion posn of extra cell
    # FIXME: be mindful of _extra_cell above when multiplicity is single
    cellLoc: 'center'
    colLabels:
      - 'Tail'    # NOTE: this is label for _extra_cell above
      - '$E[\alpha]$'
      - 'Median'
      - '$\sigma(\alpha)$'
      - 'min'
      - 'max'
    loc: 'bottom'
    bbox: [0.0, -0.26, 1.0, 0.10]

hg:   # histogram of tail-α
  Plot_cls: 'HistogramPlotter'
  fig_name: "Histogram α's - ${tsgn} tail - ${label}"
  stats2plt: ['alpha']
  _extra_lines:    # NOTE: vectors expr encoded as str; use eval() to get value
    vectors:
      - 'np.repeat(${vec_mean}, ${hist_max} + 1)'
      - 'range(0, int(${hist_max} + 1))'
    line_style:
      label: '$E[\hat{\alpha}]$'
      color: 'blue'
      linewidth: 1.5
  ax_title: |-
    Empirical distribution (${tdir}) of rolling $\hat{\alpha}$ for ${label}
    Time period: ${timeperiod}
  ax_ylabel: 'Absolute frequency'
  ax_table:
    # NOTE: _cellText_gens is prepended w/ _ b/c it's not a table-kwarg
    _cellText_gens: ['np.mean', 'np.std', 'np.min', 'np.max']
    cellLoc: 'center'
    colLabels:
      - '$E[\hat{\alpha}]$'
      - '$\sigma (\hat{\alpha})$'
      - 'min'
      - 'max'
    loc: 'bottom'
    bbox: [0.0, -0.26, 1.0, 0.10]


# #  Time Rolling FIT

ci:  # time rolling confidence interval
  Plot_cls: 'TimeRollingPlotter'
  fig_name: 'Time rolling CI - ${tdir} - ${label}'
  stats2plt: ['alpha', 'upper', 'lower']
  extra_lines:
    vectors:  # NOTE: vectors encoded as str expr; use eval() to get value
      - 'np.repeat(2, ${vec_size} + 2)'
      - 'np.repeat(3, ${vec_size} + 2)'
    line_style: {color: 'red'}
  ax_title: |-
    Rolling confidence intervals for $\alpha$-${tdir} exponents (c = ${conf_lvl}) for ${label}
    Time period: ${timeperiod}, input: ${rtrn_label}
  ax_ylabel: '$\alpha$'
  ax_legend:
    bbox_to_anchor: [0.0, -0.175, 1.0, 0.02]
    ncol: 3
    mode: 'expand'
    borderaxespad: 0

as:  # time rolling absolute size
  Plot_cls: 'TimeRollingPlotter'
  fig_name: 'Time rolling absolute size - ${tdir} - ${label}'
  stats2plt: ['abs_len']
  ax_title: |-
    Rolling absolute tail length for ${label}
    Time period: ${timeperiod}, input: ${rtrn_label}
  ax_ylabel: 'Tail length'

rs:  # time rolling relative size
  Plot_cls: 'TimeRollingPlotter'
  fig_name: 'Time rolling relative size - ${tdir} - ${label}'
  stats2plt: ['rel_len']
  ax_title: |-
    Rolling relative tail length for ${label}
    Time period: ${timeperiod}, input: ${rtrn_label}
  ax_ylabel: 'Relative tail length'

ks:  # time rolling KS-test
  Plot_cls: 'TimeRollingPlotter'
  fig_name: 'Time rolling KS test - ${tdir} - ${label}'
  stats2plt: ['ks_pv']
  ax_title: |-
    Rolling p-value via Clauset method (KS test) for ${label}
    Time period: ${timeperiod}, input: ${rtrn_label}
  ax_ylabel: 'p-value'


# # Matrix FIT

bx:  # boxplot of α-tails
  # Plot_cls: 'TimeRollingPlotter'
  fig_name: 'Boxplot - ${tsgn} tails'
  #  'stats2plt': ['α_vec']  # NOTE: this is a matrix
  ax_title: |-
    Boxplot representation of $\alpha$-${tdir} exponents
    Time period: ${timeperiod}
  ax_ylabel: '$\alpha$'
