---

# columns of the output file for analysis using a dynamic (ROLLING/INCREASING) approach

# label:
#   - date

statistics:
  - mmt_mean
  - mmt_variance
  - mmt_skewness
  - mmt_kurtosis
  - alpha
  - xmin
  # - xmin_used
  # - xmin_today  # contained in clauset_xmins_df <-- ASK/CNFRM: not add to results_df??
  - sigma
  - abs_len
  - ks_pv
  - ll_tpl
  - ll_exp
  - ll_lgn
