---

# columns of the output file for analysis using the STATIC approach

# label:
#   - ticker  # NOTE: originally termed "input"

statistics:  # NOTE: this is the name used for the Index of the column headings
  - alpha
  - xmin
  - sigma
  - abs_len
  - ks_pv
