---

# columns of the output file for analysis using a dynamic (ROLLING/INCREASING) approach

# label:
#   - date

statistics:
  - alpha
  - xmin
  # - xmin_used
  # - xmin_today
  - sigma
  - abs_len
  - ks_pv
  - ll_tpl
  - ll_exp
  - ll_lgn
