---

# columns of the output file for INDIVIDUAL tail analysis
# with a dynamic (ROLLING/INCREASING) approach

# label:
#   - date
#
# data:
#   - alpha
#   - xmin
#   - sigma
#   - abs_len
#   - ks_pv
#   - R_tpl
#   - p_tpl
#   - R_exp
#   - p_exp
#   - R_lgn
#   - p_lgn

- alpha
- xmin
- sigma
- abs_len
- ks_pv
- R_tpl
- p_tpl
- R_exp
- p_exp
- R_lgn
- p_lgn
