---

# statistics to be printed as columns in the output file

statistics:

  counts:
    - total
    - zeros
    - nonzeros

  mean:
    - all
    - pos
    - neg

  std-dev:
    - all
    - pos
    - neg

  skewness:
    - all
    - pos
    - neg

  kurtosis:
    - all
    - pos
    - neg

  tail-statistics:
    - alpha
    - xmin
    - xmax
    - xmean
    - xstdv
    - sigma
    - abs_len
    - ks_pv

  log-likelihoods:
    - tpl_R
    - tpl_p
    - exp_R
    - exp_p
    - lgn_R
    - lgn_p
