---

# statistics to be printed as columns in the output file

statistics:

  counts:
    - total
    - zeros
    - nonzeros

  moments:
    - mean
    - std-dev
    - sd_pos
    - sd_neg
    - skewness
    - skew_pos
    - skew_neg
    - kurtosis

  tail-statistics:
    - alpha
    - xmin
    - xmax
    - xmean
    - xstdv
    - sigma
    - abs_len
    - ks_pv

  log-likelihoods:
    - tpl_R
    - tpl_p
    - exp_R
    - exp_p
    - lgn_R
    - lgn_p
