---

# statistics to be printed as columns in the output file

statistics:

  returns-statistics:  # NOTE: this column label heading sits at a level higher than the two headings below
    - count
    - mean
    - std-dev
    - skewness
    - kurtosis

  tail-statistics:
    - alpha
    - xmin
    - xmax
    - xmean
    - xstdv
    - sigma
    - abs_len
    - ks_pv

  log-likelihoods:
    - tpl_R
    - tpl_p
    - exp_R
    - exp_p
    - lgn_R
    - lgn_p
