---

# all settings available to the main analysis.py module

## control settings: meta control flow of the program
ctrl:
  - interactive
  - gui
  - verbosity
  - load_options
  - save_options
  - partial_save_data

## data settings: input data and useful metadata
data:
  # - tickers  # NOTE: doesn't appear to be used
  - date_i
  - date_f
  - full_dates
  - date_i_idx
  - dynamic_dbdf
  - static_dbdf
  - anal_dates
  - grouping_type
  - grouping_labs
  - stats_colname
  - stats_collabs

## analysis settings: determines how the data is analyzed
anal:
  - approach  # TODO: make this setting needless to export; figure out how to handle rolling vs. increasing differences in initial lookback date
  - use_static  # TODO: use better name; maybe use inverse --> use_dynamic?
  - returns_type
  - lookback  # TODO: won't be needed if initial lookback handled in settings.py
  - tau
  - standardize
  - absolutize
  - tails_to_anal
  - fit_discretely
  # - xmin  # get rid of the 2 xmin settings below once this complete
  - xmin_rule
  - xmin_vqty
  - ks_flag
  - ks_iter
  - nproc

## plotting settings: needed specifically and only for plotting
plot:
  - show_plots
  - save_plots
  - title_timestamp
  # - n_vector (used in histogram, and to set xlim)
  - labelstep
  - returns_label
  - alpha_qntl
  # - alpha_signif (used in figure title of time_rolling plots)

# TODO: consider adding a sub-setting section for verbosity logging?
