---

# all settings available to the main analysis.py module

## control settings: meta control flow of the program
ctrl:
  - interactive
  - gui
  - verbosity
  - load_options
  - save_options
  - partial_save_data

## data settings: input data and useful metadata
data:
  - tickers
  - date_i
  - date_f
  - full_dates
  - date_i_idx
  - dynamic_dbdf
  - static_dbdf
  - anal_dates
  - grouping_type
  - grouping_labs
  - stats_colname
  - stats_collabs

## analysis settings: determines how the data is analyzed
anal:
  - analyze_group
  - approach
  - use_static  # TODO: use better name???
  - anal_freq
  - partition
  - returns_type
  - lookback
  - tau
  - standardize
  - absolutize
  - tails_to_use  # TODO: rename this setting
  - n_tails
  - data_nature
  - xmin_rule
  - xmin_vqty
  - ks_flag
  - ks_iter
  - nproc

plot:
  - show_plots
  - save_plots
  - title_timestamp
  # - n_vector (used in histogram, and to set xlim)
  - labelstep
  - returns_label
  - alpha_qntl
  # - alpha_signif (used in figure title of time_rolling plots)
