---

# all settings available to the main analysis.py module

## control settings: meta control flow of the program
ctrl:
  - run_gui
  # - interactive
  - verbosity
  - load_options
  - save_options
  - partial_save_data
  - nproc

## data settings: input data and useful metadata
data:
  - date_i
  - date_f
  - anal_dates
  - price_dbdf
  - grouping_type
  - grouping_labs
  - stats_colname
  - rstats_collabs  # rstats: returns statistics
  - tstats_collabs  # tstats: tail statistics
  - output_fname

## returns settings: used to calculate/preprocess the returns to be analyzed
rtrn:
  - returns_type
  - tau  # aka delta
  - dyn_win_size
  - monthly_bounds  # only used for the 'monthly' approach
  - standardize
  - absolutize
  - norm_target
  - norm_before
  - norm_after

## analysis settings: determines how the data is analyzed
anal:
  - approach  # TODO: needless to export if rolling_window_type known/constructed in settings.py
  - use_dynamic
  - get_dyn_lbd  # bound method used in analysis.py for getting the lookback date label for logging
  - tails_to_anal
  - fit_discretely
  - xmin_rule
  - xmin_qnty
  - txmin_map  # only used by xmin_rule 'file' OR 'average'
  # - clauset_xmins_df  # contains value of xmin_today <-- ASK/CNFRM: not add to results_df
  - run_ks_test
  - ks_iter
  - compare_distros  # TODO: add warning informing ignored if '-a static'

## plotting settings: needed specifically and only for plotting
plot:
  - plot_results
  - show_plots
  - save_plots
  - title_timestamp
  # - n_vector (used in histogram, and to set xlim)
  - labelstep
  - returns_label
  - alpha_qntl
  # - alpha_signif (used in figure title of time_rolling plots)

# TODO: consider adding a sub-setting section for verbosity logging?
