---

# all settings available to the main analysis.py module

## control settings: meta control flow of the program
ctrl:
  - interactive
  - gui
  - verbosity
  - load_options
  - save_options
  - partial_save_data
  - nproc

## data settings: input data and useful metadata
data:
  # - tickers  # NOTE: doesn't appear to be used
  - date_i
  - date_f
  - anal_dates
  - raw_dbdf
  - grouping_type
  - grouping_labs
  - stats_colname
  - stats_collabs

## analysis settings: determines how the data is analyzed
anal:
  - approach  # TODO: needless to export if rolling_window_type known/constructed in settings.py
  - use_dynamic
  - returns_type
  - tau
  - window_size
  - standardize
  - absolutize
  - norm_target
  - norm_before
  - norm_after
  - tails_to_anal
  - fit_discretely
  # - xmin  # get rid of the 2 xmin settings below once this complete
  - xmin_rule
  - xmin_vqty
  - run_ks_test
  - ks_iter

## plotting settings: needed specifically and only for plotting
plot:
  - show_plots
  - save_plots
  - title_timestamp
  # - n_vector (used in histogram, and to set xlim)
  - labelstep
  - returns_label
  - alpha_qntl
  # - alpha_signif (used in figure title of time_rolling plots)

# TODO: consider adding a sub-setting section for verbosity logging?
