---

# all settings available to the main analysis.py module

## control settings: meta control flow of the program
ctrl:
  - run_gui
  # - interactive
  - verbosity
  - load_options
  - save_options
  - partial_save_data
  - nproc

## data settings: input data and useful metadata
data:
  - date_i
  - date_f
  - anal_dates
  - price_dbdf
  - grouping_type
  - grouping_labs
  - stats_colname
  - rstats_collabs  # rstats: returns statistics
  - tstats_collabs  # tstats: tail statistics
  - outputs_dirname # directory to store the analysis results and plots (if any)
  - output_fname
  - clauset_xmins_df  # only generated when Clauset xmins calculated from scratch w/ 'average' xmin rule

## returns settings: used to calculate/preprocess the returns to be analyzed
rtrn:
  - returns_type
  - tau  # aka delta
  - dyn_win_size
  - monthly_bounds  # only used for the 'monthly' approach
  - standardize
  - absolutize
  - norm_target
  - norm_before
  - norm_after

## analysis settings: determines how the data is analyzed
anal:
  - approach
  - use_dynamic
  - get_dyn_lbd  # bound method used in analysis.py for getting the lookback date label for logging
  - tails_to_anal
  - fit_discretely
  - xmin_rule
  - xmin_qnty
  - txmin_map  # only used by xmin_rule 'file' OR 'average'
  - calc_rtrn_stats
  - run_ks_test
  - ks_iter
  - compare_distros

## plotting settings: needed specifically and only for plotting
plot:
  - plot_results
  - show_plots
  - save_plots
  - title_timeperiod
  - vec_size
  - xtick_locs
  - xtick_labs
  - returns_label
  - confidence_level
  - alpha_quantile
  - plot_combos

# TODO: add sub-setting for output data formatting?
# TODO: consider adding a sub-setting section for verbosity logging?
