---

# options attributes for all forms of tail analysis

lookback:
  param_decls:
    # - '-l'
    - '--lookback'
  type: 'int'
  default: 504
  help: 'lookback (in days) to use for rolling analysis'

returns_type:
  param_decls:
    - '-r'
    - '--returns-type'
    # - '--rtype'
    # - 'returns_type'
  type:  # TODO: consider using Enum types for all Choice values
    - 'basic'
    - 'relative'
    - 'log'
  default: 'log'
  help: 'specify the type of returns to analyse'

tau:
  param_decls:
    - '--tau'
    # - 'delta'  # ASK: is 'delta' more fitting?
  type: 'int'  # TODO: provide as (str) choices of discrete ints
  default: 1
  help: 'specify the time lag (in days) of the input series'

# ASK: need to specify std/abs targets if approach is static?
standardize: 
  param_decls:
    - '--std/--no-std'
    - 'standardize'
  is_flag: true
  # type: 'bool'  # TODO: cast to proper click.BOOL type
  default: false
  help: 'standardize/normalize the input data'

absolutize:
  param_decls:
    - '--abs/--no-abs'
    - 'absolutize'
  is_flag: true
  # type: 'bool'
  default: false
  help: 'take the absolute value of the input data'

approach:
  param_decls:
    - '-a'
    - '--approach'
  type:
    - 'static'
    - 'rolling'
    - 'increasing'
  default: 'rolling'
  help: ''

# NOTE: --analyze-freq only applies to non-static approaches
# anal_freq: 1
# sliding_window: 1

partition:
  param_decls:
    - '-p'
    - '--partition'
  type:
    - 'country'
    - 'maturity'
    - 'core_vs_peripheral'
    - 'all'
    - 'none'
  default: null
  hidden: true
  help: 'method for grouping tickers'

tail_selection:
  param_decls:
    - '-t'
    - '--tail'
    - 'tail_selection'
  type:  # TODO: consider using feature switch(es)?
    - 'left'
    - 'right'
    - 'both'
    # TODO: allow specifying as mult-val: ex. '--tails left right'
  default: 'both'
  help: 'choose the tail(s) to analyse'

data_nature:
  param_decls:
    - '-n'
    - '--data-nature'
  type:
    - 'discrete'
    - 'continuous'
  default: 'continuous'
  help: ''

# xmin_rule: 'average'
# xmin_extra: 'average'

alpha_signif:
  param_decls:
    - '--alpha'
    - 'alpha_significance'
  type: 'float'
  default: 0.05
  help: 'significance of the confidence interval: 1-Î±'

plpva_iter:
  param_decls:
    - '--plpva-iter'
    # - '--piter'
    # - 'plpva_iter'
  type: 'int'
  default: 100
  help: 'Clauset p-value algorithm num of iterations'

show_plots:
  param_decls:
    - '--show-plots/--no-show-plots'
    # - 'show_plots'
  is_flag: true
  # type: 'bool'
  default: true
  help: ''

save_plots:
  param_decls:
    - '--save-plots/--no-save-plots'
    # - 'save_plots'
  is_flag: true
  # type: 'bool'
  default: false
  help: ''
