---

# options attributes for all forms of tail analysis

analyze_group:
  param_decls:
    - '-G'
    - '--group/--individual'
    - 'analyze_group'
  is_eager: true
  default: false
  callback: 'gset_group_opts'
  help: 'set flag to run in group analysis mode; use with --help to also see options specific to group analysis'

tickers:  # TODO: allow passing in a .txt file of tickers?
  param_decls:
    - '--tickers'
  cls: 'VnargsOption'
  separator: ','
  type: 'list'
  default:
    - 'DE 01Y'
    - 'DE 03Y'
    - 'DE 05Y'
    - 'DE 10Y'
      # metavar: '[ <csv on CLI> | <.csv> | <.txt> ]'  # TODO: file options
  # callback: 'set_tickers_from_textfile'
  metavar: '<csv on CLI>'
  help: 'specify the list of tickers from the database to analyse'

# TODO: use callback to validate dates?
date_i:
  param_decls:
    - '-di'
    - '--date-initial'
    - 'date_i'
  type: 'str'  # TODO: use dedicated Date type
  # default: '31-03-16'
  default: '1/1/2016'
  metavar: ''
  help: 'the starting date of the time series to analyse'

date_f:
  param_decls:
    - '-df'
    - '--date-final'
    - 'date_f'
  type: 'str'  # TODO: use dedicated Date type
  default: '5/5/2016'
  metavar: ''
  help: 'the final date of the time series to analyse'

returns_type:
  param_decls:
    - '-r'
    - '--returns-type'
    # - '--rtype'
    # - 'returns_type'
  type:  # TODO: consider using Enum types for all Choice values
    - 'raw'
    - 'relative'
    - 'log'
  default: 'log'
  help: 'specify the type of returns to analyse'

tau:
  param_decls:
    - '--tau'
    # - 'delta'  # ASK: is 'delta' more fitting?
  type:
    - '1'
    - '5'
    - '22'
  default: '1'
  callback: 'cast_tau'
  metavar: '[1 (daily) | 5 (weekly) | 22 (monthly)]'
  help: 'specify the time lag (in days) of the input series'

# ASK: need to specify std/abs targets if approach is static?
standardize: 
  param_decls:
    - '--std/--no-std'
    - 'standardize'
  is_flag: true
  # type: 'bool'  # TODO: cast to proper click.BOOL type
  default: false
  help: 'standardize/normalize the input data'

# TODO use VnargsOption to allow specify target
# TODO: OR use feature switches for series/tail // before/after/both
absolutize:
  param_decls:
    - '--abs/--no-abs'
    - 'absolutize'
  is_flag: true
  # type: 'bool'
  default: false
  help: 'take the absolute value of the input data'

approach_args:
  param_decls:
    - '-a'
    - '--approach'
    - 'approach_args'  # FIXME: use 'approach' in errmsgs not 'approach_args'
  cls: 'VnargsOption'
  max_nargs: 2
  is_eager: true
  type: 'tuple'
  default:
    # NOTE: this default map is NOT actually used by the click.Option,
    #       but is instead here for convenient serialization/encoding
    rolling: '1'
    increasing: '1'
    static: null  # TODO: default it to 1 as well for convenience?
  show_default: false
  callback: 'validate_approach_args'
  # metavar:
  help: >
    for 'rolling' or 'increasing', optionally specify <INT (# days)>
    as the analysis frequency, default: 1
# ASK/CONFIRM: anal_freq (in normal) == sliding_window (in group)

# ASK/CONFIRM: lookback is ONLY needed by dynamic approaches
# TODO add 'lookback' as additional arg to 'approach_args' VnargsOption??
lookback:  # NOTE: only applies to non-static approaches
  param_decls:
    - '-l'
    - '--lookback'
  type: 'int'
  default: 504
  callback: 'gset_lookback'
  metavar: '<INT (# days)>'
  help: 'lookback (in days) to use for rolling or increasing approaches (N/A for static)'

partition:  # NOTE: only applicable w/ -G (group tail analysis) enabled
  param_decls:
    - '-p'
    - '--partition'
  type:
    - 'country'
    - 'maturity'
    - 'region'  # i.e. core (DE, FR, BE) vs. periphery (IT, ES, PT, IR, GR)
    - 'all'
    # - 'none'
  default: null
  callback: 'confirm_group_flag_set'
  hidden: true
  help: 'method for aggregating tickers for group tail analysis'

# TODO: use VnargsOption for --tail ??
tail_selection:
  param_decls:
    - '-t'
    - '--tail'
    - 'tail_selection'
  type:  # TODO: consider using feature switch(es)?
    - 'left'
    - 'right'
    - 'both'
    # TODO: allow specifying as mult-val: ex. '--tails left right'
  default: 'both'
  help: 'choose the tail(s) to analyse'

data_nature:
  param_decls:
    - '-n'
    - '--data-nature'
  type:
    - 'discrete'
    - 'continuous'
  default: 'continuous'
  help: ''

xmin_args:
  param_decls:
    - '-x'
    - '--xmin'
    - 'xmin_args'  # TODO: use 'xmin' in errmsgs not 'xmin_args'
  cls: 'VnargsOption'
  max_nargs: 3
  type: 'tuple'
  default:
    # NOTE: this default map is NOT actually used by the click.Option,
    #       but is instead here for convenient serialization/encoding
    clauset: null
    manual: '0'
    percentile: '90'
  show_default: false
  callback: 'validate_xmin_args'
  # metavar: NOTE: this attr is set by the _set_xmin_metavar_help call
  help: |  # FIXME: newline below not preserved in --help
    -manual: float value, default: 0
    -percentile: 0-100, default: 90

alpha_signif:
  param_decls:
    - '--alpha'
    - 'alpha_signif'
  type: 'float'
  default: 0.05
  metavar: '<FLOAT: [0, 1]>'
  help: 'significance of the confidence interval: 1-Î±'

ks_flag:
  param_decls:
    - '--ks-run/--ks-skip'
    - 'ks_flag'
  is_eager: true  # NOTE: is_eager needed to correctly customize show_default in help via cb
  default: true
  metavar: '(Run/Skip KS-Test)'  # FIXME: get metavarto work w/ flags (not shown currently)
  callback: 'customize_ksflag_show_default'
  help: '--ks-skip overrides value from --ks-iter'

# TODO: make VnargsOption work with flags, then combine ks-iter & --ks-run
ks_iter:
  param_decls:
    - '--ks-iter'
  type: 'int'
  default: 100
  metavar: '<INT (# iterations)>'
  help: 'specify number of iterations used for KS-testing'

show_plots:
  param_decls:
    - '--show-plots/--no-show-plots'
    # - 'show_plots'
  is_flag: true
  # type: 'bool'
  default: true
  help: ''

save_plots:
  param_decls:
    - '--save-plots/--no-save-plots'
    # - 'save_plots'
  is_flag: true
  # type: 'bool'
  default: false
  help: ''
