---

# options attributes for all forms of tail analysis

# TODO: consider adding the full_dbdf argument declaration in here?
# also create another config file to specify the order in which the
# params & CBs are to be parsed/fired?

analyze_group:
  param_decls:
    - '-G'
    - '--group/--individual'
    - 'analyze_group'
  is_eager: true  # NOTE: eagerness of this opt also helps to dynamically set --help of -G-dependent opts
  default: false
  callback: 'gset_group_opts'
  help: 'set flag to run in group analysis mode; -Gh to see group-specific help'

tickers:  # TODO: allow passing in a .txt file of tickers?
  param_decls:
    - '-T'
    - '--tickers'
  cls: 'VnargsOption'
  separator: ','
  type: 'list'
  default:
    - 'DE 01Y'
    - 'DE 03Y'
    - 'DE 05Y'
    - 'DE 10Y'
  # metavar: '[ <csv on CLI> | <.csv> | <.txt> ]'
  # callback: 'set_tickers_from_textfile'
  metavar: '<csv on CLI>'
  help: 'specify list of tickers from DB to analyze'

# TODO: use specialized Date type (ex. pd.DatetimeIndex) for correct metavar
# and/or alternatively, use callback to validate (likely more cumbersome)
date_i:
  param_decls:
    - '--di'
    - '--date-initial'
    - 'date_i'
  type: 'str'
  # default: '1/4/2016'  # NOTE: unset 'default' attr to infer date_i
  default: '2/5/2016'  # <--- very short date range for testing/debugging
  metavar: ''  # NOTE: metavar set to '' here so it doesn't show up as 'TEXT'
  help: 'first date to analyze'

date_f:
  param_decls:
    - '--df'
    - '--date-final'
    - 'date_f'
  type: 'str'
  default: '5/5/2016'  # NOTE: unset 'default' attr to infer date_f
  metavar: ''  # NOTE: metavar set to '' here so it doesn't show up as 'TEXT'
  help: 'final date to analyze'

approach_args:
  param_decls:
    - '-a'
    - '--approach'
    - 'approach_args'
  cls: 'VnargsOption'
  max_nargs: 3
  is_eager: true  # NOTE: eagerness required to set lookback for the gset_full_dbdf cb
  type: 'tuple'
  default:
    # NOTE: this default map is NOT actually used by the click.Option,
    #       but is instead here for convenient serialization/encoding
    rolling:
      - '504'
      - '1'
    increasing:
      - '504'
      - '1'
    static:
      - null
      - null
  show_default: false
  callback: 'validate_approach_args'
  # metavar:  # NOTE: this attr is set by _set_vnargs_choice_metahelp_()
  help: >
    opt args for 'rolling' or 'increasing': <(ℤ⁺, ℤ⁺)| # days: (lookback,
    analysis-frequency)>  [defaults: (504, 1)]
# ASK/CONFIRM: anal_freq (in normal) == sliding_window (in group)

partition:  # NOTE: opt only available in group tail analysis mode
  param_decls:
    - '-p'
    - '--partition'
  type:
    - 'country'
    - 'maturity'
    - 'region'  # i.e. core (DE, FR, BE) vs. periphery (IT, ES, PT, IR, GR)
    - 'all'
    - 'none'  # TODO: this should just run individual analysis mode
  default: null
  callback: 'confirm_group_flag_set'
  hidden: true  # hide option when using individual tail analysis mode
  help: 'how to group tickers for group tail analysis'

returns_type:
  param_decls:
    - '--rt'
    - '--returns-type'
    - 'returns_type'
  type:  # TODO: consider using Enum types for all Choice values
    - 'raw'
    - 'relative'
    - 'log'
  default: 'log'
  help: 'specify the type of returns to analyze'

tau:
  param_decls:
    - '--tau'
    # - 'delta'  # ASK/TODO: isn't 'delta' more fitting varname?
  type: 'int'
  default: 1
  # callback: 'cast_tau'
  metavar: '<ℤ⁺>'
  # metavar: '[1 (daily) | 5 (weekly) | 22 (monthly)]'
  help: 'specify time lag <# days> of the input series'

standardize: 
  param_decls:
    - '--std'
    - '--standardize/--no-std'
    - 'standardize'
  is_flag: true
  default: false
  help: 'standardize [(X-μ)/σ] input data'

# TODO: create alias -N, --norm for std + abs ??

absolutize:
  param_decls:
    - '--abs'
    - '--absolutize/--no-abs'
    - 'absolutize'
  is_flag: true
  default: false
  help: 'take absolute value of input data'

norm_target:  # NOTE: only available in individual mode & for the static approach
  param_decls:
    - '--norm-series/--norm-tail'  # use boolean flag to fake the 2 mutually exclusive choices
    - 'norm_target'
  is_flag: true
  default: true  # {series: true, tail: false}
  callback: 'validate_norm_target'
  help: "-std +/ -abs TARGET when using '-a static'"

norm_before:  # NOTE: opt only available in group tail analysis mode
  param_decls:
    - '--nb'
    - '--norm-before'
    - 'norm_before'
  is_flag: true
  default: false  # set to false in default individual mode so ctx.get_parameter_source works
  show_default: false
  hidden: true  # hide option when using individual tail analysis mode
  help: 'std +/ abs BEFORE and/or AFTER grouping tickers  [default: both]'

norm_after:  # NOTE: opt only available in group tail analysis mode
  param_decls:
    - '--na'
    - '--norm-after'
    - 'norm_after'
  is_flag: true
  default: false  # set to false in default individual mode so ctx.get_parameter_source works
  show_default: false
  hidden: true  # hide option when using individual tail analysis mode
  help: 'set either --norm-before OR --norm-after to ONLY normalize then'

anal_right:
  param_decls:
    - '-R/--right-skip'
    - 'anal_right'
  is_flag: true
  default: true  # default to True so if neither tail set, then both analyzed
  help: '-R w/o -L to analyze right tail ONLY'

anal_left:
  param_decls:
    - '-L/--left-skip'
    - 'anal_left'
  is_flag: true
  default: true  # default to True so if neither tail set, then both analyzed
  help: '-L w/o -R to analyze left tail ONLY'

alpha_signif:
  param_decls:
    - '--alpha'
    - 'alpha_signif'
  type: 'float'
  default: 0.05
  metavar: '<ℝ ∊ [0, 1]>'
  help: 'significance of the confidence interval: 1-α'

# TODO/ASK: remove below option? since nature of data can be inferred from database
#           also confirm result of using discrete-fit on continous data; vice versa
data_nature:
  param_decls:
    - '--data-nature'
  type:
    - 'discrete'
    - 'continuous'
  default: 'continuous'
  help: 'discrete ~ ℤ data vs. continuous ~ ℝ data'

xmin_args:
  param_decls:
    - '-x'
    - '--xmin'
    - 'xmin_args'
  cls: 'VnargsOption'
  max_nargs: 3
  type: 'tuple'
  default:
    # NOTE: this default map is NOT actually used by the click.Option,
    #       but is instead here for convenient serialization/encoding
    clauset: null
    percentile: '90'
    manual: '0'
  show_default: false
  callback: 'validate_xmin_args'
  # metavar:  # NOTE: this attr is set by _set_vnargs_choice_metahelp_()
  help: |  # FIXME: newline(s) below not preserved in --help (adding blank spaces does it, but is janky)
    percentile: <ℝ ∊ [0-100]>  [default: 90]                   
    manual: <ℝ >  [default: 0]
# 'manual' & 'percentile' rules accept an optional numeric arg:
# FIXME/TODO: improve help message above & for similar opts (i.e. approach_args)

run_ks_test:
  param_decls:
    - '--ks-run/--ks-skip'
    - 'run_ks_test'
  default: true
  metavar: '(Run/Skip KS-Test)'  # FIXME: get metavar to work w/ flags (not shown currently)
  help: 'NOTE: --ks-skip overrides --ks-iter'

# TODO: consider add similar skip option as above for logl_stats??

# TODO: make VnargsOption work with flags, then combine --ks-iter & --ks-run?
ks_iter:
  param_decls:
    - '--ks-iter'
  type: 'int'
  default: 100
  metavar: '<ℤ⁺>'
  help: 'specify # iterations to use for KS-testing'

# TODO: hide control & plotting options from --help unless specified by some subcommand/flag (to reduce clutter)

nproc:
  param_decls:
    - '-N'
    - '--nproc'
  type: 'int'
  # default: 1  # NOTE: set 'default' here to override current behavior of using os.cpu_count()
  callback: 'gset_nproc_default'
  metavar: '<ℤ⁺>'
  help: "# of concurrent processes to use"

show_plots:
  param_decls:
    - '--show-plots/--no-show-plots'
    # - 'show_plots'
  is_flag: true
  # type: 'bool'  # TODO: cast this (& others) to proper click.BOOL type?
  default: true
  help: ''

save_plots:
  param_decls:
    - '--save-plots/--no-save-plots'
    # - 'save_plots'
  is_flag: true
  default: false
  help: ''
