---

# defaults values specific to group tail analysis

partition: 'country'

lookback: 252

xmin_args:
  average:  # NOTE: only available in dynamic (rolling & increasing) approaches 
    - '66'
    - '0'
  clauset: null
  manual: '0'
  percentile: '90'
  # help: |  # NOTE: this is set by the _set_xmin_metavar_help call
  #   -average: 2 INTs (# days) - sliding window & lag, default: 66, 0
  #   -manual: float value, default: 0
  #   -percentile: 0-100, default: 90

ks_flag: false

ks_iter: 2

# TODO: allow modding other attrs besides 'default' in this config?
