---

# defaults values specific to group tail analysis

analyze_group: true

approach_args:
  rolling: ['252', '1']
  increasing: ['252', '1']
  monthly: [null, 1]
  static: [null, null]

lb_override: 252

partition: 'country'
# TODO: --tickers like option for selecting group(s) to analyze (i.e. specify 'DE' when in country)

# NOTE: when either --std OR --abs set w/o any timing flags below, both timing opts
# will default to value set in conditionalize_normalization_options_ of options.py
norm_before: false
norm_after: false  # true if either --std OR --abs set w/o timing specified

xmin_args:
  - "average"  # NOTE: defaults for 'average' set in parse_xmin_args() in options.py
  - "clauset"
  - "%"
  - "ℝ "
  - "XMINS_FILE"

run_ks_test: false

ks_iter: 2

compare_distros: false

# help: # TODO: customize --help for group?
