---

# defaults values specific to group tail analysis

# TODO: allow modding other attrs besides 'default' in this config?

partition: 'country'
# TODO: --tickers like option for selecting group(s) to analyze (i.e. specify 'DE' when in country)

lookback: 252

norm_before: false
norm_after: false  # TODO: can set default value directly here?

xmin_args:
  average:  # only available for dynamic approaches (rolling & increasing)
    - '66'  # rolling window period in days
    - '0'   # rolling lag in days
    - null  # filepath containing pre-calc'd xmin values used to compute average xmin
  clauset: null
  manual: '0'
  percentile: '91.41'

run_ks_test: false

ks_iter: 2

# help: # TODO: customize --help for group?
