---

# defaults values specific to group tail analysis

# TODO: allow modding other attrs besides 'default' in this config?

analyze_group: true

approach_args:
  rolling:
    - '252'
    - '1'
  increasing:
    - '252'
    - '1'
  static:
    - null
    - null

lb_override: 252

partition: 'country'
# TODO: --tickers like option for selecting group(s) to analyze (i.e. specify 'DE' when in country)

norm_before: false
norm_after: false  # TODO: can set default value directly here?

xmin_args:
  - "average"  # TODO: defaults for 'average' set in parse_xmin_args() in options.py
  - "clauset"
  - "%"
  - "ℝ "
  - "XMINS_FILE"

run_ks_test: false

ks_iter: 2

compare_distros: false

# help: # TODO: customize --help for group?
