---

# defaults values specific to group tail analysis

# TODO: allow modding other attrs besides 'default' in this config?

partition: 'country'

lookback: 252

# TODO/ASK: what should the default be if either -std/-abs set, but no timings set?
norm_before: false
norm_after: false
# TODO: create alias for both before + after ???

xmin_args:
  average:  # only available for dynamic approaches (rolling & increasing)
    - '66'
    - '0'
    - null  # TODO: file path for Clauset-calc'd xmins
  clauset: null
  manual: '0'
  percentile: '90'

run_ks_test: false

ks_iter: 2

# help: # TODO: customize --help for group?
