---

# defaults values specific to group tail analysis

# TODO: allow modding other attrs besides 'default' in this config?

partition: 'country'

lookback: 252

xmin_args:
  average:  # NOTE: only available in dynamic (rolling & increasing) approaches 
    - '66'
    - '0'
  clauset: null
  manual: '0'
  percentile: '90'

run_ks_test: false

ks_iter: 2

# help: # TODO: customize --help for group?
