---

# defaults values specific to group tail analysis

# TODO: allow modding other attrs besides 'default' in this config?

partition: 'country'
# TODO: --tickers like option for selecting group(s) to analyze (i.e. specify 'DE' when in country)

lookback: 252

norm_before: false
norm_after: false  # TODO: can set default value directly here?

xmin_args:
  average:  # only available for dynamic approaches (rolling & increasing)
    - '66'
    - '0'
    - null  # TODO: file path for Clauset-calc'd xmins
  clauset: null
  manual: '0'
  percentile: '90'

run_ks_test: false

ks_iter: 2

# help: # TODO: customize --help for group?
